unit class CSS::Specification::Compiler::Make;

use CSS::Specification::Compiler :&build-metadata;

use NativeCall;

sub path(RakuAST::Package $p) {
    $p.name.parts>>.name.join: '/';
}

method make-module($where, $meta-root, @sources, :%inherit, :$link) {
    my %props;

    indir $where, {
        my Array @base-ids;
        my %seen;

        my @group-id = $meta-root.split('::');
        note "Building $meta-root";

        for @sources {
            my ($class-path, $files) = .isa(Pair) ?? .kv !! ([], $_);
            my @base-id = flat @group-id, @$class-path, <Gen>;
            my @grammar-id = @base-id.Slip, 'Grammar';
            my $scope := 'unit';
            my @defs;
            my CSS::Specification::Compiler $compiler .= new;
            for $files.List -> $file {
                note " - " ~ $file ~ (%seen{$file}++ ?? ' (duplicate)' !! '');
                @defs.append: $compiler.load-defs(:$file);
            }

            mkdir 'lib/' ~ @base-id.join('/');
            my RakuAST::Package $grammar-ast = $compiler.compile-grammar(@grammar-id, :$scope);
            "lib/{$grammar-ast.&path}.rakumod".IO.spurt: $grammar-ast.DEPARSE;

            my @actions-id = @base-id.Slip, 'Actions';
            my RakuAST::Package $actions-ast = $compiler.compile-actions(@actions-id, :$scope);
            "lib/{$actions-ast.&path}.rakumod".IO.spurt: $actions-ast.DEPARSE;

            my @external-id = @base-id.Slip, 'External';
            my RakuAST::Package $external-ast = $compiler.compile-external(@external-id, :$scope);
            "lib/{$external-ast.&path}.rakumod".IO.spurt: $external-ast.DEPARSE;

            my %child-rules = $compiler.child-rules;
            my %child-props = $compiler.child-props;
            my %meta = @defs.&build-metadata(:%child-rules, :%child-props);
            %props{.key} //= .value for %meta.pairs;
            @base-ids.push: @base-id;
        }

        %props{.key} //= .value for %inherit.pairs;

        %props.&write-metadata($meta-root);

        if $link {
            my @actions-link-id = flat @group-id, 'Actions';
            my @grammar-link-id = flat @group-id, 'Grammar';
            my @external-link-id = flat @group-id, 'External';
            # my @use-ids = @module-ids.map: { .Slip, 'Actions' }
            # RakuAST version nyi (Raku v2026.05)
            # my RakuAST::Package $actions-package = CSS::Specification::Compiler.link-actions(@actions-link-id, @module-ids);
            # "lib/{$actions-package.&path}.rakumod".IO.spurt: $actions-package.DEPARSE;
            ("lib/" ~ @actions-link-id.join('/') ~ ".rakumod").IO.spurt:  link-actions(@actions-link-id, @base-ids);
            ("lib/" ~ @grammar-link-id.join('/') ~ ".rakumod").IO.spurt:  link-grammar(@grammar-link-id, @base-ids);
            ("lib/" ~ @external-link-id.join('/') ~ ".rakumod").IO.spurt: link-external(@external-link-id, @base-ids);
        }
    }
    %props;
}


# Non-RakuAST implementations
sub link-actions(@group-id, @modules) {
    my @lines = 'unit class ' ~  @group-id.join('::') ~ ';';
    @lines.push: '';
    for @modules {
        my $name = (.Slip, 'Actions').join('::');
        @lines.push: "use {$name};";
        @lines.push: "also is {$name};";
    }
    @lines.push('').join: "\n";
}

sub link-grammar(@group-id, @modules) {
    my @lines = 'unit grammar ' ~  @group-id.join('::') ~ ';';
    @lines.push: '';
    for @modules {
        my $name = (.Slip, 'Grammar').join('::');
        @lines.push: "use {$name};";
        @lines.push: "also is {$name};";
    }
    @lines.join("\n") ~ "\n";
}

sub link-external(@group-id, @modules) {
    my @lines = 'unit role ' ~  @group-id.join('::') ~ ';';
    @lines.push: '';
    for @modules {
        my $name = (.Slip, 'External').join('::');
        @lines.push: "use {$name};";
        @lines.push: "also does {$name};";
    }
    @lines.join("\n") ~ "\n";
}

sub write-metadata(%props, $meta) {
    my $class-dir = $*SPEC.catdir(<lib>, $meta.split('::').Slip);
    my $class-path = $*SPEC.catfile( $class-dir, 'Metadata.rakumod' );
    my $class-name = "{$meta}::Metadata";
    {
        my $*OUT = open $class-path, :w;
        say "#  -- DO NOT EDIT --";
        say "# generated by: $*PROGRAM-NAME {@*ARGS}".trim;
        say 'use NativeCall;';
        say 'use CSS::Module::Property;';
        say '';
        say "module $class-name \{";
        say "    BEGIN our \$property = {%props.item.raku};";
        # todo: BEGIN our \$index = ... ; ## Missing serialize REPR function for REPR
        say '    our enum prop-names <' ~ %props.keys.sort.join(' ') ~ '>;';
        say q:to<END>;
            our sub index {
                state $ //= do {
                    my $enums := prop-names.enums;
                    CArray[CSS::Module::Property].new: |$property.sort.map({CSS::Module::Property.new(:$enums, name => .key, |.value)});
                }
            }
        }
        END
        $*OUT.close;
    }
}
